package space.gatt.pocketbot.utils.enums;

public enum ReactionEvent {

	SUBSCRIBE, SUBSCRIBE_RECURRING, PRIME_SUBSCRIBE_RECURRING, PRIME_SUBSCRIBE,
	SUBSCRIBE_T1_OVERRIDE, SUBSCRIBE_T2_OVERRIDE, SUBSCRIBE_T3_OVERRIDE, SUBSCRIBE_T1_OVERRIDE_RECURRING, SUBSCRIBE_T2_OVERRIDE_RECURRING, SUBSCRIBE_T3_OVERRIDE_RECURRING,
	GIFT_SUBS,
	RAID, HOST;
}
